apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
        name: redis-server
    spec:
      containers:
      - name: redis
        image: redis:5.0
        ports:
          - name: redis
            containerPort: 6379
        volumeMounts:
          - name: volv
            mountPath: /data
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: local-path-redis
