# kubectl -n <k8s-namespace> create secret docker-registry alembik --docker-server=ghcr.io --docker-username=<github-username> --docker-password=<github-personal-access-token>  --docker-email=<email-address>

apiVersion: batch/v1
kind: CronJob
metadata:
  name: hacker-news-deployment
spec:
  schedule: "15 */4 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          initContainers:
            - name: hacker-news-producer
              image: ghcr.io/gabrielepicco/alembik/alembik-producer
              env:
              - name: SOURCE
                value: hackernews
              - name: MONGO_HOST
                value: mongodb
              - name: MONGO_DB
                value: alembik
              imagePullPolicy: Always
          containers:
            - name: hacker-news-instagram-consumer
              image: ghcr.io/lucacillario/alembik/alembik-instagram-consumer:latest
              env:
              - name: MONGO_HOST
                value: mongodb
              - name: MONGO_DB
                value: alembik
              - name: ACCOUNT
                value: hackernews
              - name: LOGGING_LEVEL
                value: debug
              imagePullPolicy: Always
          imagePullSecrets:
            - name: alembik
          restartPolicy: Never
