apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-redis
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
