# kubectl -n <k8s-namespace> create secret docker-registry alembik --docker-server=ghcr.io --docker-username=<github-username> --docker-password=<github-personal-access-token>  --docker-email=<email-address>

apiVersion: batch/v1
kind: CronJob
metadata:
  name: reddit-news-deployment
  labels:
    app: reddit-news
spec:
  schedule: "0 */4 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          initContainers:
            - name: reddit-news-producer
              image: ghcr.io/gabrielepicco/alembik/alembik-producer
              env:
              - name: SOURCE
                value: "reddit"
              - name: SUBREDDIT
                value: "news"
              - name: MONGO_HOST
                value: "mongodb"
              - name: MONGO_DB
                value: "alembik"
              imagePullPolicy: Always
          containers:
            - name: reddit-news-instagram-consumer
              image: ghcr.io/lucacillario/alembik/alembik-instagram-consumer:latest
              env:
              - name: MONGO_HOST
                value: "mongodb"
              - name: MONGO_DB
                value: "alembik"
              - name: ACCOUNT
                value: reddit-news
              - name: LOGGING_LEVEL
                value: debug
              imagePullPolicy: Always
          imagePullSecrets:
            - name: alembik
          restartPolicy: Never
