# kubectl -n <k8s-namespace> create secret docker-registry alembik --docker-server=ghcr.io --docker-username=<github-username> --docker-password=<github-personal-access-token>  --docker-email=<email-address>

apiVersion: batch/v1
kind: CronJob
metadata:
  name: reddit-news-producer-deployment
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: reddit-news-producer
              image: ghcr.io/gabrielepicco/alembik/alembik-producer
              env:
              - name: SOURCE
                value: "reddit"
              - name: SUBREDDIT
                value: "news"
              - name: MONGO_HOST
                value: "mongodb"
              - name: MONGO_DB
                value: "alembik"
              imagePullPolicy: Always
          imagePullSecrets:
            - name: alembik
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: reddit-news-static-website-deployment
spec:
  schedule: "10 */1 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: reddit-news-static-website-consumer
              image: ghcr.io/lucacillario/alembik/alembik-instagram-consumer:latest
              env:
              - name: MONGO_HOST
                value: mongodb
              - name: MONGO_DB
                value: alembik
              - name: ACCOUNT
                value: reddit-news
              - name: SOCIAL
                value: static_website
              - name: LOGGING_LEVEL
                value: debug
              imagePullPolicy: Always
          imagePullSecrets:
            - name: alembik
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: reddit-news-instagram-deployment
spec:
  schedule: "10 */3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: reddit-news-instagram-consumer
              image: ghcr.io/lucacillario/alembik/alembik-instagram-consumer:latest
              env:
              - name: MONGO_HOST
                value: "mongodb"
              - name: MONGO_DB
                value: "alembik"
              - name: ACCOUNT
                value: reddit-news
              - name: LOGGING_LEVEL
                value: debug
              imagePullPolicy: Always
          imagePullSecrets:
            - name: alembik
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: reddit-news-twitter-deployment
spec:
  schedule: "10 */1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: reddit-news-twitter-consumer
              image: ghcr.io/lucacillario/alembik/alembik-instagram-consumer:latest
              env:
              - name: MONGO_HOST
                value: "mongodb"
              - name: MONGO_DB
                value: "alembik"
              - name: ACCOUNT
                value: reddit-news
              - name: LOGGING_LEVEL
                value: debug
              - name: SOCIAL
                value: twitter
              imagePullPolicy: Always
          imagePullSecrets:
            - name: alembik
          restartPolicy: Never