# kubectl -n <k8s-namespace> create secret docker-registry alembik --docker-server=ghcr.io --docker-username=<github-username> --docker-password=<github-personal-access-token>  --docker-email=<email-address>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo
          image: mongo:4.2
          ports:
            - name: mongo
              containerPort: 27017
          volumeMounts:
            - name: volv
              mountPath: /data/db
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: mongo-volume
