name: RedditFunny - Produce and Consume

# Controls when the workflow will run
on:
  
  schedule:
  - cron: '0 */3 * 1 *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  produce:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gabrielepicco/alembik/alembik-producer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
      env:
        SOURCE: reddit
        SUBREDDIT: funny
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DB: alembik
        USE_DEEP_LEARNING: true
    steps:
      - name: Produce
        working-directory: /app
        run: python -m alembik
        
  consume-instagram:
    needs: produce
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lucacillario/alembik/alembik-instagram-consumer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
      env:
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DB: alembik
        SOCIAL: instagram
        LOGGING_LEVEL: debug
        ACCOUNT: reddit-funny
    steps:
      - name: Consume twitter
        working-directory: /app
        run: python -m alembik
